apiVersion: v1

kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql-container
  image: sonoflion/wpteam:v.1
  # env:
  # - name: SERVER_NAME
  #   value: wpteam-mysqlserver.mysql.database.azure.com
  # - name: USER_NAME
  #   value: mysqladminun@wpteam-mysqlserver
  # - name: USER_PASSWORD
  #   value: H@Sh1CoR3!
  # command: ["sh", "-c"]
  # args:
  # - |
  #   apk add --no-cache mysql-client
  #   mysql -h $SERVER_NAME -u $USER_NAME -p$USER_PASSWORD -P 3306 -e "\
  #     CREATE TABLE IF NOT EXISTS my_table (id INT PRIMARY KEY, name VARCHAR(50)); \
  #     INSERT INTO my_table (id, name) VALUES (1, 'John'), (2, 'Jane'), (3, 'Joe');"
