version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
    - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: pi
      WORDPRESS_DB_PASSWORD:
      WORDPRESS_DB_NAME: exampledb
    volumes:
    - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: Adminp
      MYSQL_PASSWORD:
      MYSQL_RANDOM_ROOT_PASSWORD: ''
    volumes:
    - db:/var/lib/mysql

volumes:
  wordpress:
  db:
