apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
  spec:
    initContainers:
    - name: init
      image: sonoflion/wpteam:v.3
      volumeMounts:
      - name: wordpress-persistent-storage
        mountPath: /var/www/html

  containers:
  - name: wordpress
    image: wordpress:latest
    env:
    - name: WORDPRESS_DB_HOST
      value: "wpteam-mysqlserver.mysql.database.azure.com"
    - name: WORDPRESS_DB_NAME
      value: "test_manifest12"
    - name: WORDPRESS_DB_USER
      value: "mysqladminun@wpteam-mysqlserver"
    - name: WORDPRESS_DB_PASSWORD
      value: "H@Sh1CoR3!"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: wordpress-persistent-storage
      mountPath: /var/www/html

  volumes:
  - name: wordpress-persistent-storage
    persistentVolumeClaim:
      claimName: wp-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
