apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-pr-trigger-binding
spec:
  params:
  - name: gitRepository
    value: $(body.repository.html_url))
  - name: commits
    value: $(body.commits)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-pr-trigger-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
      generateName: my-pipeline-
      spec:
      serviceAccountName: docker-login
      pipelineRef:
        name: pipeline1
      podTemplate: 
        securityContext: 
          fsGroup: 65532
      params:
      - name: revision
        value: main
      - name: repo-url
        value: "https://github.com/LeonidPistryi/Azure-ActionDeploy"
      - name: docker-image
        value: "docker.io/sonoflion/wpteam"
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-pr
spec:
  serviceAccountName: docker-login
  triggers:
    - name: pr-trigger
      interceptors:
        - ref:
            name: "github"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
          - name: "pipeline"
            value:
              secretName: github-trigger-secret
              secretKey: secretToken
          - name: "eventTypes"
            value: ["push"]
          - name: "branches"
            value: ["main"]
      bindings:
        - ref: github-pr-trigger-binding
      template:
        ref: github-pr-trigger-template
