apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: git-push-binding
spec:
  params:
  - name: gitRepository
    value: $(body.repository.html_url)
  - name: commits
    value: $(body.commits)
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: docker-login-rolebinding
subjects:
- kind: ServiceAccount
  name: docker-login
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: git-push-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: clonebuildpushrun-
      spec:
        serviceAccountName: docker-login
        pipelineRef:
          name: clonebuildpush
        podTemplate:
          securityContext:
            fsGroup: 65532  
        params:
          - name: revision
            value: main
          - name: gitrepositoryurl
            value: "https://github.com/LeonidPistryi/Azure-ActionDeploy"
          - name: IMAGE
            value: "docker.io/sonoflion/wpteam"
          - name: TAG
            value: v1
        workspaces:
          - name: workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Gi   
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: git-push-listener
spec:
  serviceAccountName: docker-login
  triggers:
    - name: git-push-trigger
      interceptors:
        - ref:
            name: "github"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
          - name: "pipeline"
            value:
              secretName: github-trigger-secret
              secretKey: secretToken
          - name: "eventTypes"
            value: ["push"]
          - name: "branches"
            value: ["main"]
      bindings:
        - ref: git-push-binding
      template:
        ref : git-push-template
