apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline1
spec:
  params:
    - name: revision
    - name: repo-url
    - name: docker-image
      description: Path to the Dockerfile to build.
      default: ../Dockerfile
  workspaces:
    - name: workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
      params:
        - name: revision
          value: $(params.revision)
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: "true"
    - name: build-push-image
      taskRef:
        name: buildah
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: workspace
      params:
        - name: IMAGE
          value: "$(params.docker-image):latest"
        - name: FORMAT
          value: "docker"
          