apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: my-pipeline-
spec:
  serviceAccountName: docker-login
  pipelineRef:
    name: pipeline1
  podTemplate: 
    securityContext: 
      fsGroup: 65532
  params:
  - name: revision
    value: main
  - name: repo-url
    value: "https://github.com/LeonidPistryi/Azure-ActionDeploy"
  - name: docker-image
    value: "docker.io/sonoflion/wpteam"
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi