apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-wordpress-image
spec:
  tasks:
    - name: build-image
      taskRef:
        name: build-wordpress-image
      params:
        - name: IMAGE
          value: my-wordpress-image
      resources:
        inputs:
          - name: source
            resource: https://github.com/LeonidPistryi/Azure-ActionDeploy
        outputs:
          - name: image
            resource: my-docker-image
    - name: push-image
      taskRef:
        name: docker push sonoflion/wpteam:v.14
      params:
        - name: IMAGE_URL
          valueFrom:
            resource: sonoflion/wpteam:v.14
      resources:
        inputs:
          - name: image
            resource: sonoflion/wpteam:v.14
