apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  annotations:
    tekton.dev/docker-0: https://index.docker.io/
type: kubernetes.io/basic-auth
stringData:
    username: sonoflion
    password: Vges680h9
---
apiVersion: v1
kind: Secret
metadata:
  name: github-trigger-secret
type: Opaque
stringData:
  secretToken: "123"
--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-login
secrets:
  - name: docker-secret
  - name: github-trigger-secret
  - name: git-ssh-key