name: My-GithubActions-Basics

on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:

  terraform:
    runs-on: ubuntu-latest

    env:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    # user-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Terraform Format
      id: fmt
      run: terraform fmt

    - name: Terraform Init
      id: init
      run: terraform init

    - name: 'Az CLI login using OIDC'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      # with:
      #   client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #   tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #   subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #   user-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
